// RUN: choco-opt -p riscv-ssa-to-riscv "%s" | filecheck "%s"

builtin.module {
  "choco_ir.func_def"() <{"func_name" = "_main", "return_type" = !choco_ir.named_type<"<None>">}> ({
  ^0:
  }) : () -> ()
}

// CHECK:       builtin.module {
// CHECK-NEXT:    "choco_ir.func_def"() <{"func_name" = "_main", "return_type" = !choco_ir.named_type<"<None>">}> ({
// CHECK-NEXT:      "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -4 : i64, "comment" = "Reserve space for ra"}> : () -> ()
// CHECK-NEXT:      "riscv.sw"() <{"rs1" = !riscv.reg<ra>, "rs2" = !riscv.reg<sp>, "immediate" = 0 : i64, "comment" = "Store return address"}> : () -> ()
// CHECK-NEXT:      "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 0 : i64, "comment" = "Reserve stack space for spilled registers"}> : () -> ()
// CHECK-NEXT:      "riscv.mv"() <{"rd" = !riscv.reg<tp>, "rs" = !riscv.reg<sp>, "comment" = "Move main stack pointer to special register"}> : () -> ()
// CHECK-NEXT:      "riscv.comment"() : () -> ()
// CHECK-NEXT:      "riscv.comment"() <{"comment" = "Footer Ops"}> : () -> ()
// CHECK-NEXT:      "riscv.label"() <{"label" = #riscv.label<__main_return>}> : () -> ()
// CHECK-NEXT:      "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 0 : i64, "comment" = "Free stack space reserved for spilled registers"}> : () -> ()
// CHECK-NEXT:      "riscv.lw"() <{"rd" = !riscv.reg<ra>, "rs1" = !riscv.reg<sp>, "immediate" = 0 : i64, "comment" = "Store return address"}> : () -> ()
// CHECK-NEXT:      "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 4 : i64, "comment" = "Free space for ra"}> : () -> ()
// CHECK-NEXT:      "riscv.comment"() : () -> ()
// CHECK-NEXT:      "riscv.comment"() <{"comment" = "Exit program"}> : () -> ()
// CHECK-NEXT:      "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:      "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 93 : i64}> : () -> ()
// CHECK-NEXT:      "riscv.ecall"() : () -> ()
// CHECK-NEXT:    }) : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_print_int>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -12 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<t1>, "rs" = !riscv.reg<a0>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t2>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t1>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t1>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t5>, "immediate" = 2 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mul"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t6>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t5>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sub"() <{"rd" = !riscv.reg<t5>, "rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t6>}> : () -> ()
// CHECK-NEXT:    "riscv.mul"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t1>}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<t6>, "rs" = !riscv.reg<zero>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 9 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 8 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 7 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 6 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 5 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 3 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 2 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.rem"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<t0>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slt"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<zero>, "rs2" = !riscv.reg<a0>}> : () -> ()
// CHECK-NEXT:    "riscv.slt"() <{"rd" = !riscv.reg<t5>, "rs1" = !riscv.reg<a0>, "rs2" = !riscv.reg<zero>}> : () -> ()
// CHECK-NEXT:    "riscv.or"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<t4>, "rs2" = !riscv.reg<t5>}> : () -> ()
// CHECK-NEXT:    "riscv.and"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t3>, "rs2" = !riscv.reg<t4>}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.div"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.slti"() <{"rd" = !riscv.reg<t5>, "rs1" = !riscv.reg<t5>, "immediate" = -1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t5>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t5>, "immediate" = 45 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<sp>, "rs2" = !riscv.reg<t6>}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t4>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t4>, "immediate" = -1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.slt"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t4>, "rs2" = !riscv.reg<a0>}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 11 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a1>, "rs" = !riscv.reg<sp>}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<a1>, "rs1" = !riscv.reg<a1>, "rs2" = !riscv.reg<t6>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a2>, "immediate" = 12 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sub"() <{"rd" = !riscv.reg<a2>, "rs1" = !riscv.reg<a2>, "rs2" = !riscv.reg<t6>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 64 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 12 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ret"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_print_bool>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -16 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 70 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 97 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 108 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 2 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 115 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 3 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 5 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 6 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 84 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 7 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 8 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 117 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 9 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 11 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 12 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t1>, "immediate" = 7 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sltu"() <{"rd" = !riscv.reg<t2>, "rs1" = !riscv.reg<zero>, "rs2" = !riscv.reg<a0>}> : () -> ()
// CHECK-NEXT:    "riscv.mul"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<sp>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t3>, "immediate" = 6 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sltu"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<zero>, "rs2" = !riscv.reg<a0>}> : () -> ()
// CHECK-NEXT:    "riscv.sub"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<t3>, "rs2" = !riscv.reg<t4>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a1>, "rs" = !riscv.reg<t1>}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a2>, "rs" = !riscv.reg<t4>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 64 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 16 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ret"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_print_str>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<a0>, "immediate" = 0 : i64, "comment" = "Get address of string object"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t2>, "rs1" = !riscv.reg<t0>, "immediate" = 0 : i64, "comment" = "Load length of string"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t1>, "immediate" = 0 : i64, "comment" = "Set loop counter to zero"}> : () -> ()
// CHECK-NEXT:    "riscv.sub"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "rs2" = !riscv.reg<t2>, "comment" = "Expand stack pointer by number of string elements"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -1 : i64, "comment" = "Expand stack pointer for newline"}> : () -> ()
// CHECK-NEXT:    "riscv.beq"() <{"rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>, "offset" = #riscv.label<_print_str_loop_finished>}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_print_str_loop_header>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t6>, "immediate" = 4 : i64, "comment" = "Number of bytes per element"}> : () -> ()
// CHECK-NEXT:    "riscv.mul"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t6>, "comment" = "Distance from pointer in bytes"}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<t3>, "comment" = "The address of the element in the string"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t5>, "rs1" = !riscv.reg<t4>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<sp>, "rs2" = !riscv.reg<t1>, "comment" = "The address of the element on the stack"}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t4>, "immediate" = 0 : i64, "comment" = "Store character on stack"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<t1>, "immediate" = 1 : i64, "comment" = "Increment loop counter"}> : () -> ()
// CHECK-NEXT:    "riscv.bne"() <{"rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<t2>, "offset" = #riscv.label<_print_str_loop_header>, "comment" = "Continue loop"}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_print_str_loop_finished>}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<sp>, "rs2" = !riscv.reg<t1>, "comment" = "The address of the element on the stack"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t5>, "immediate" = 10 : i64, "comment" = "Store newline character in output string"}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t4>, "immediate" = 0 : i64, "comment" = "Store character on stack"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64, "comment" = "Print to stdout"}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a1>, "rs" = !riscv.reg<sp>, "comment" = "syscall argument: the start address is the stack pointer"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t2>, "immediate" = 1 : i64, "comment" = "Make room for newline"}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a2>, "rs" = !riscv.reg<t3>, "comment" = "syscall argument: length of the string"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 64 : i64, "comment" = "Request the print system call"}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() <{"comment" = "Trigger the system call"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 1 : i64, "comment" = "Free the stack for newline"}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "rs2" = !riscv.reg<t2>, "comment" = "Free the stack"}> : () -> ()
// CHECK-NEXT:    "riscv.ret"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_input>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -1024 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<ra>, "rs2" = !riscv.reg<sp>, "immediate" = 1020 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a1>, "rs" = !riscv.reg<sp>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a2>, "immediate" = 1020 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 63 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t1>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<t4>, "rs" = !riscv.reg<a0>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<t4>, "immediate" = -1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mul"() <{"rd" = !riscv.reg<a0>, "rs1" = !riscv.reg<a0>, "rs2" = !riscv.reg<t1>}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<a0>, "rs1" = !riscv.reg<a0>, "rs2" = !riscv.reg<t1>}> : () -> ()
// CHECK-NEXT:    "riscv.jal"() <{"rd" = !riscv.reg<ra>, "offset" = #riscv.label<_malloc>, "comment" = "Allocate memory for new list"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t1>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<t4>, "rs2" = !riscv.reg<a0>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t5>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.beq"() <{"rs1" = !riscv.reg<t4>, "rs2" = !riscv.reg<t5>, "offset" = #riscv.label<_input_loop_finished>}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_input_loop_header>}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<sp>, "rs2" = !riscv.reg<t5>}> : () -> ()
// CHECK-NEXT:    "riscv.lb"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t3>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mul"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t1>}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<a0>, "rs2" = !riscv.reg<t3>}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<t6>, "rs2" = !riscv.reg<t3>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t5>, "rs1" = !riscv.reg<t5>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.bne"() <{"rs1" = !riscv.reg<t4>, "rs2" = !riscv.reg<t5>, "offset" = #riscv.label<_input_loop_header>}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_input_loop_finished>}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<ra>, "rs1" = !riscv.reg<sp>, "immediate" = 1020 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 1024 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ret"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_list_concat>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -24 : i64, "comment" = "Reserve stack space"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<a0>, "immediate" = 0 : i64, "comment" = "Load length of list a"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<a1>, "immediate" = 0 : i64, "comment" = "Load length of list b"}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t2>, "rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<t1>, "comment" = "Compute length of overall list"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t3>, "immediate" = 4 : i64, "comment" = "Load size of a word in bytes"}> : () -> ()
// CHECK-NEXT:    "riscv.mul"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<t2>, "rs2" = !riscv.reg<t3>, "comment" = "Compute amount of storage for list elements"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<t4>, "immediate" = 4 : i64, "comment" = "Also consider space needed to store list size"}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<ra>, "rs2" = !riscv.reg<sp>, "immediate" = 0 : i64, "comment" = "Save return address"}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 4 : i64, "comment" = "Save length of list a"}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<sp>, "immediate" = 8 : i64, "comment" = "Save length of list b"}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<t2>, "rs2" = !riscv.reg<sp>, "immediate" = 12 : i64, "comment" = "Save length of new list"}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<a0>, "rs2" = !riscv.reg<sp>, "immediate" = 16 : i64, "comment" = "Save base ptr of list a"}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<a1>, "rs2" = !riscv.reg<sp>, "immediate" = 20 : i64, "comment" = "Save base ptr of list b"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<a0>, "rs1" = !riscv.reg<t4>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.jal"() <{"rd" = !riscv.reg<ra>, "offset" = #riscv.label<_malloc>, "comment" = "Allocate memory for new list"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<ra>, "rs1" = !riscv.reg<sp>, "immediate" = 0 : i64, "comment" = "Restore return address"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<sp>, "immediate" = 4 : i64, "comment" = "Restore length of list a"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<sp>, "immediate" = 8 : i64, "comment" = "Restore length of list b"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t2>, "rs1" = !riscv.reg<sp>, "immediate" = 12 : i64, "comment" = "Restore length of new list"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<sp>, "immediate" = 16 : i64, "comment" = "Restore base ptr of list a"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<sp>, "immediate" = 20 : i64, "comment" = "Restore base ptr of list b"}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<t2>, "rs2" = !riscv.reg<a0>, "immediate" = 0 : i64, "comment" = "Store length of new list in list"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t5>, "immediate" = 0 : i64, "comment" = "Set loop counter"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<a0>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.beq"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<zero>, "offset" = #riscv.label<_list_concat_repeat_first_end>}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_list_concat_repeat_first>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t5>, "rs1" = !riscv.reg<t5>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t3>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t2>, "rs1" = !riscv.reg<t3>, "immediate" = 0 : i64, "comment" = "Load list element from a"}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<t2>, "rs2" = !riscv.reg<t6>, "immediate" = 0 : i64, "comment" = "Store list element in new list"}> : () -> ()
// CHECK-NEXT:    "riscv.bne"() <{"rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t0>, "offset" = #riscv.label<_list_concat_repeat_first>}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_list_concat_repeat_first_end>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t5>, "immediate" = 0 : i64, "comment" = "Set loop counter"}> : () -> ()
// CHECK-NEXT:    "riscv.beq"() <{"rs1" = !riscv.reg<t1>, "rs2" = !riscv.reg<zero>, "offset" = #riscv.label<_list_concat_repeat_second_end>}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_list_concat_repeat_second>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t5>, "rs1" = !riscv.reg<t5>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<t4>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t6>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t2>, "rs1" = !riscv.reg<t4>, "immediate" = 0 : i64, "comment" = "Load list element from a"}> : () -> ()
// CHECK-NEXT:    "riscv.sw"() <{"rs1" = !riscv.reg<t2>, "rs2" = !riscv.reg<t6>, "immediate" = 0 : i64, "comment" = "Store list element in new list"}> : () -> ()
// CHECK-NEXT:    "riscv.bne"() <{"rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t1>, "offset" = #riscv.label<_list_concat_repeat_second>}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_list_concat_repeat_second_end>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 24 : i64, "comment" = "Free stack space"}> : () -> ()
// CHECK-NEXT:    "riscv.ret"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_str_eq>}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t0>, "rs1" = !riscv.reg<a0>, "immediate" = 0 : i64, "comment" = "Load length of first string"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t1>, "rs1" = !riscv.reg<a1>, "immediate" = 0 : i64, "comment" = "Load length of second string"}> : () -> ()
// CHECK-NEXT:    "riscv.bne"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<t1>, "offset" = #riscv.label<_str_eq_return_false>, "comment" = "return false if length are not equal"}> : () -> ()
// CHECK-NEXT:    "riscv.beq"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<zero>, "offset" = #riscv.label<_str_eq_return_true>, "comment" = "return true if both length are equal to 0"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t2>, "rs1" = !riscv.reg<a0>, "immediate" = 4 : i64, "comment" = "First string index iterator"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<a1>, "immediate" = 4 : i64, "comment" = "Second string index iterator"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t5>, "immediate" = 4 : i64, "comment" = "Size of an integer"}> : () -> ()
// CHECK-NEXT:    "riscv.mul"() <{"rd" = !riscv.reg<t5>, "rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<t5>, "comment" = "Size of the strings in bytes"}> : () -> ()
// CHECK-NEXT:    "riscv.add"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<a0>, "rs2" = !riscv.reg<t5>, "comment" = "First string iterator last element"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t4>, "rs1" = !riscv.reg<t4>, "immediate" = 4 : i64, "comment" = "First string end iterator"}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_str_eq_loop_begin>}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t5>, "rs1" = !riscv.reg<t2>, "immediate" = 0 : i64, "comment" = "Get the first string character"}> : () -> ()
// CHECK-NEXT:    "riscv.lw"() <{"rd" = !riscv.reg<t6>, "rs1" = !riscv.reg<t3>, "immediate" = 0 : i64, "comment" = "Get the first string character"}> : () -> ()
// CHECK-NEXT:    "riscv.bne"() <{"rs1" = !riscv.reg<t5>, "rs2" = !riscv.reg<t6>, "offset" = #riscv.label<_str_eq_return_false>, "comment" = "If the characters are different, return false"}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t2>, "rs1" = !riscv.reg<t2>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<t3>, "rs1" = !riscv.reg<t3>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.blt"() <{"rs1" = !riscv.reg<t2>, "rs2" = !riscv.reg<t4>, "offset" = #riscv.label<_str_eq_loop_begin>, "comment" = "If we are not at the end of the string, continue"}> : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_str_eq_return_true>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ret"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_str_eq_return_false>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ret"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_error_len_none>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -52 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 84 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 121 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 112 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 2 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 3 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 69 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 5 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 6 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 7 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 8 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 58 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 9 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 11 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 98 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 12 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 106 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 13 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 14 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 99 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 15 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 116 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 16 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 17 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 18 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 102 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 19 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 20 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 116 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 21 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 121 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 22 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 112 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 23 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 24 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 25 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 39 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 26 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 78 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 27 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 28 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 110 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 29 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 30 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 84 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 31 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 121 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 112 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 33 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 34 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 39 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 35 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 36 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 104 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 37 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 97 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 38 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 115 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 39 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 40 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 110 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 41 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 42 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 43 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 108 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 44 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 45 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 110 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 46 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 40 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 47 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 41 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a1>, "rs" = !riscv.reg<sp>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a2>, "immediate" = 49 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 64 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 52 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.comment"() : () -> ()
// CHECK-NEXT:    "riscv.comment"() <{"comment" = "Exit program"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 93 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_list_index_oob>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -36 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 73 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 110 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 100 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 2 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 3 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 120 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 69 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 5 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 6 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 7 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 8 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 9 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 58 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 11 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 108 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 12 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 105 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 13 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 115 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 14 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 116 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 15 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 16 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 105 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 17 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 110 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 18 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 100 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 19 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 20 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 120 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 21 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 22 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 23 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 117 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 24 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 116 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 25 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 26 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 27 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 102 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 28 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 29 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 30 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 97 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 31 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 110 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 103 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 33 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 34 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a1>, "rs" = !riscv.reg<sp>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a2>, "immediate" = 35 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 64 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 36 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.comment"() : () -> ()
// CHECK-NEXT:    "riscv.comment"() <{"comment" = "Exit program"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 93 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_list_index_none>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -52 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 84 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 121 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 112 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 2 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 3 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 69 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 5 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 6 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 7 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 8 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 58 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 9 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 39 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 11 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 78 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 12 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 13 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 110 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 14 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 15 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 84 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 16 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 121 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 17 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 112 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 18 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 19 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 39 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 20 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 21 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 22 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 98 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 23 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 106 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 24 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 25 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 99 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 26 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 116 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 27 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 28 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 105 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 29 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 115 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 30 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 31 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 110 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 33 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 116 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 34 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 35 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 115 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 36 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 117 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 37 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 98 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 38 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 115 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 39 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 99 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 40 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 41 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 105 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 42 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 112 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 43 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 116 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 44 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 97 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 45 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 98 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 46 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 108 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 47 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 48 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a1>, "rs" = !riscv.reg<sp>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a2>, "immediate" = 49 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 64 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 52 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.comment"() : () -> ()
// CHECK-NEXT:    "riscv.comment"() <{"comment" = "Exit program"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 93 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.label"() <{"label" = #riscv.label<_error_div_zero>}> : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = -28 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 68 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 0 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 105 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 118 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 2 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 66 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 3 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 121 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 4 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 90 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 5 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 6 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 7 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 8 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 58 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 9 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 10 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 68 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 11 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 105 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 12 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 118 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 13 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 105 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 14 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 115 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 15 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 105 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 16 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 17 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 110 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 18 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 19 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 98 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 20 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 121 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 21 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 32 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 22 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 122 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 23 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 101 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 24 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 114 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 25 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<t0>, "immediate" = 111 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.sb"() <{"rs1" = !riscv.reg<t0>, "rs2" = !riscv.reg<sp>, "immediate" = 26 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.mv"() <{"rd" = !riscv.reg<a1>, "rs" = !riscv.reg<sp>}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a2>, "immediate" = 27 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 64 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:    "riscv.addi"() <{"rd" = !riscv.reg<sp>, "rs1" = !riscv.reg<sp>, "immediate" = 28 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.comment"() : () -> ()
// CHECK-NEXT:    "riscv.comment"() <{"comment" = "Exit program"}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a0>, "immediate" = 1 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.li"() <{"rd" = !riscv.reg<a7>, "immediate" = 93 : i64}> : () -> ()
// CHECK-NEXT:    "riscv.ecall"() : () -> ()
// CHECK-NEXT:  }
